services:
    cadvisor:
        image: gcr.io/cadvisor/cadvisor:latest
        container_name: cadvisor
        restart: always
        privileged: true
        depends_on:
            - postgres
        volumes:
            - /etc:/etc
        ports:
            - 8080:8080
        networks:
            - app-network
        logging:
            driver: json-file
            options:
                max-size: 10m
                max-file: 3

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        image: node:22-bookworm-slim
        container_name: frontend
        depends_on:
            - backend
            - postgres
        command: "npm start"
        ports:
            - 5173:5173
        networks:
            - app-network
        logging:
            driver: json-file
            options:
                max-size: 10m
                max-file: 3

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: node:22-bookworm-slim
        container_name: backend
        volumes:
            - ./backend:/usr/src/app
        depends_on:
            - postgres
        ports:
            - 3001:3001
        networks:
            - app-network
        logging:
            driver: json-file
            options:
                max-size: 10m
                max-file: 3

    postgres:
        image: postgres:latest
        container_name: postgres
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - app-network
            - adminer-network
        logging:
            driver: json-file
            options:
                max-size: 10m
                max-file: 3

    adminer:
        image: adminer
        container_name: adminer
        volumes:
            - ./adminer_config.php:/var/www/html/config.php
        depends_on:
            - postgres
        ports:
            - "8081:8080"
        restart: always
        networks:
            - adminer-network
        logging:
            driver: json-file
            options:
                max-size: 10m
                max-file: 3

networks:
    app-network:
        driver: bridge
    adminer-network:
        driver: bridge
volumes:
    postgres_data:
        driver: local
